# Generated by Django 3.0.8 on 2020-07-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate", models.CharField(max_length=6)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
            ],
            options={"abstract": False,},
        ),
    ]
