# Generated by Django 3.0.8 on 2020-07-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
